version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8080"
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
  rocketmq:
    image: rocketmq-4.9.x
    ports:
      - "9876:9876"