brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
listenPort=10911

# IMPORTANT: inside docker network, do NOT use localhost
namesrvAddr=rocketmq-namesrv:9876

brokerIP1=rocketmq-broker

storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
